# netlify.toml

# 빌드 설정을 정의합니다.
[build]
  # 빌드 시 실행할 명령어입니다. requirements.txt에 명시된 라이브러리를 설치합니다.
  command = "pip install -r requirements.txt"
  # 서버리스 함수가 위치한 디렉토리를 지정합니다.
  functions = "netlify/functions/"

# [functions] 블록 전체를 삭제합니다.

# 모든 요청을 서버리스 함수로 보내는 규칙을 설정합니다.
[[redirects]]
  # 웹사이트의 모든 경로(/*)로 들어오는 요청을
  from = "/*"
  # 'api' 라는 이름의 서버리스 함수로 전달합니다.
  to = "/.netlify/functions/api/:splat"
  # HTTP 상태 코드 200은 URL 변경 없이 내부적으로 처리하라는 의미입니다.
  status = 200
  force = true
