# netlify.toml

# 빌드 설정을 정의합니다.
[build]
  # 빌드 시 실행할 명령어입니다. requirements.txt에 명시된 라이브러리를 설치합니다.
  command = "pip install -r requirements.txt"
  # 서버리스 함수가 위치한 디렉토리를 지정합니다.
  functions = "netlify/functions/"
  # 정적 파일이 없으므로, 이 항목은 필요 없거나 현재 디렉토리를 가리켜도 됩니다.
  # publish = "." 

# 서버리스 함수에 대한 추가 설정을 정의합니다.
[functions]
  # Python 런타임 사용을 명시적으로 포함합니다.
  included_files = ["netlify/functions/api.py"]

# 모든 요청을 서버리스 함수로 보내는 규칙을 설정합니다.
[[redirects]]
  # 웹사이트의 모든 경로(/, /about, /anything 등)로 들어오는 요청을
  from = "/*"
  # 'api' 라는 이름의 서버리스 함수로 전달합니다.
  # 'api.py' 파일을 사용했으므로 '/.netlify/functions/api'가 됩니다.
  to = "/.netlify/functions/api/:splat"
  # HTTP 상태 코드 200은 URL을 변경하지 않고 내부적으로 처리하라는 의미입니다.
  status = 200
  force = true
