[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions/" # Netlify가 함수를 찾을 디렉토리

[[redirects]]
  # 모든 요청을 'main' 함수로 전달합니다.
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200 # 200 OK 상태 코드로 리라이트(rewrite)합니다.
  force = true
