[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions/"

# [functions] 블록을 추가하여 main.py의 handler를 명시적으로 지정합니다.
[functions]
  # 이 설정은 'main.py' 파일의 'handler' 객체를
  # 'main'이라는 이름의 함수로 만들도록 Netlify에 지시합니다.
  included_files = ["netlify/functions/main.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
  force = true
